repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: end-of-file-fixer

- repo: https://github.com/pycqa/pylint
  rev: v2.16.2
  hooks:
    - id: pylint
      args:
        - "--rcfile=.pylintrc"
      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/

- repo: https://github.com/google/yapf
  rev: v0.32.0
  hooks:
  - id: yapf

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.0
  hooks:
    - id: mypy

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v15.0.7'
  hooks:
  - id: clang-format
    types_or: [c++, c]

- repo: https://github.com/mwouts/jupytext
  rev: v1.14.4
  hooks:
  - id: jupytext
    args: [--sync]
