target-version = "py310"
line-length = 108
indent-width = 2
respect-gitignore = true
exclude = ["third_party"]
fix = true
show-fixes = true

[lint]
select = [
  "E", "F", "W", "I", "N", "UP", "B", "C4", "RUF"
]

ignore = [
  "E731", "B905", "C901", "B006",
  "N802", "N803", "N806", "N812", "N813", "N815", "N818"
]

[lint.pep8-naming]
ignore-names = ["foo", "bar"]
extend-ignore-names = ["baz"]
classmethod-decorators = ["classmethod"]
staticmethod-decorators = ["staticmethod"]

[format]
quote-style = "double"
line-ending = "lf"
indent-style = "space"
skip-magic-trailing-comma = true

[lint.isort]
force-single-line = false
known-third-party = ["absl", "enchant"]
combine-as-imports = true
